version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./server/uploads:/usr/src/app/uploads
      - ./server/src:/usr/src/app/src

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  db-data:
